(function(){'use strict';
var CONFIG=window.DOTYK_V2||{};
var icons={search:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg>',account:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.7-4 3-6 7-6s6.3 2 7 6"/></svg>',heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 5.7a5.1 5.1 0 0 0-7.2 0L12 7.3l-1.6-1.6a5.1 5.1 0 0 0-7.2 7.2L12 21l8.8-8.1a5.1 5.1 0 0 0 0-7.2Z"/></svg>',cart:'<svg class="ds-fashion-cart-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 8h12l-1 12H7L6 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></svg>',menu:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>'};
var phrases=['mám toho dosť','nevolaj mi','citovo nedostupný','overthinking','mikiny','veci, ktoré nepovieš nahlas'];
function $(s,r){return(r||document).querySelector(s)}function $$(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
function menuItems(){var tops=$$('#navigation .menu-level-1>li').map(function(li){var a=li.querySelector(':scope>a');if(!a)return null;var kids=$$(':scope>.menu-level-2>li>a,:scope>ul>li>a',li).map(function(x){return{text:(x.textContent||'').trim(),href:x.href}}).filter(function(x){return x.text});return{text:(a.textContent||'').trim(),href:a.href,children:kids}}).filter(Boolean);var shop=tops.find(function(x){return /shop|obchod|produkty/i.test(x.text)});if(shop&&shop.children.length>=2){var others=tops.filter(function(x){return x!==shop});return shop.children.map(function(x){return{text:x.text,href:x.href,children:[]}}).concat(others)}return tops}
function announcement(items){var bar=$('.top-navigation-bar'),box=bar&&$('.container',bar);if(!bar||!box)return;bar.classList.add('ds-fashion-announcement');if($('.ds-fashion-announcement__link',box))return;var n=items.find(function(x){return/novink|new/i.test(x.text)}),a=document.createElement('a');a.className='ds-fashion-announcement__link';a.textContent='NOVÝ DROP JE VONKU →';a.href=CONFIG.announcementUrl||(n&&n.href)||'#';if(a.getAttribute('href')==='#')a.onclick=function(e){e.preventDefault()};box.append(a)}
function renderNav(items){var top=$('#header .header-top'),logo=top&&$('.site-name-wrapper',top);if(!top||!logo||!items.length)return false;var old=$('.ds-live-nav',top);if(old)old.remove();var ul=document.createElement('ul');ul.className='ds-live-nav';ul.setAttribute('aria-label','Hlavná navigácia');items.slice(0,9).forEach(function(item){if(!item.text)return;var li=document.createElement('li');li.className='ds-live-nav__item';if(item.children&&item.children.length){var b=document.createElement('button');b.type='button';b.className='ds-live-nav__button';b.textContent=item.text;b.setAttribute('aria-expanded','false');var d=document.createElement('div');d.className='ds-live-nav__dropdown';d.innerHTML='<ul>'+item.children.slice(0,12).map(function(c){return'<li><a href="'+c.href+'">'+c.text+'</a></li>'}).join('')+'</ul>';b.onclick=function(){var open=!li.classList.contains('is-open');$$('.ds-live-nav__item.is-open',ul).forEach(function(o){o.classList.remove('is-open')});li.classList.toggle('is-open',open);b.setAttribute('aria-expanded',open?'true':'false')};li.append(b,d)}else{var a=document.createElement('a');a.className='ds-live-nav__link';a.href=item.href;a.textContent=item.text;li.append(a)}ul.append(li)});logo.insertAdjacentElement('afterend',ul);document.body.classList.add('ds-custom-nav-ready');return true}
function action(cls,label,svg,href){var e=document.createElement(href?'a':'button');if(href)e.href=href;else e.type='button';e.className='ds-fashion-action '+cls;e.setAttribute('aria-label',label);e.innerHTML=svg;return e}
function wishCount(){try{var d=JSON.parse(localStorage.getItem('dotykWishlist')||'[]');return Array.isArray(d)?d.length:0}catch(e){return 0}}
function syncWish(){var b=$('.ds-fashion-wishlist .ds-fashion-count');if(!b)return;var n=wishCount();b.dataset.count=String(n);b.textContent=String(n)}
function mountActions(){var box=$('#header .navigation-buttons'),cart=box&&$('.cart-count',box);if(!box||!cart)return;$$('.ds-approved-action,.ds-v2-action,.ds-fashion-action',box).forEach(function(n){n.remove()});var search=action('ds-fashion-search-trigger','Hľadať',icons.search);search.insertAdjacentHTML('beforeend','<span>Hľadať</span>');var wish=action('ds-fashion-wishlist','Obľúbené',icons.heart);wish.insertAdjacentHTML('beforeend','<span class="ds-fashion-count" data-count="0">0</span>');wish.onclick=function(){document.dispatchEvent(new CustomEvent('DotykWishlistOpen'))};var acc=action('ds-fashion-account toggle-window','Môj účet',icons.account,'#');acc.dataset.target='login';box.insertBefore(search,cart);box.insertBefore(wish,cart);box.insertBefore(acc,cart);$$('svg',cart).forEach(function(x){x.remove()});cart.insertAdjacentHTML('afterbegin',icons.cart);syncWish();search.onclick=openSearch}
function searchTop(){var h=$('#header.ds-fashion-header');if(h)document.documentElement.style.setProperty('--ds-search-top',Math.max(0,Math.round(h.getBoundingClientRect().bottom))+'px')}
function openSearch(){document.body.classList.remove('navigation-window-visible');document.body.classList.add('ds-fashion-search-open');searchTop();setTimeout(function(){var i=$('.ds-fashion-search-overlay .search-input');if(i)i.focus()},40)}function closeSearch(){document.body.classList.remove('ds-fashion-search-open')}
function mountSearch(){var native=$('#header .search'),input=native&&$('.search-input',native),btn=native&&$('.search-form .btn',native);if(!native||!input||$('.ds-fashion-search-overlay'))return;var o=document.createElement('div');o.className='ds-fashion-search-overlay';o.innerHTML='<div class="ds-fashion-search-overlay__inner"><div class="ds-fashion-search-overlay__top"><span class="ds-fashion-search-overlay__label">Hľadať v Dotyku</span><button class="ds-fashion-search-close" type="button">×</button></div><div class="ds-fashion-search-slot"></div><div class="ds-fashion-search-suggestions"></div><div class="ds-fashion-search-results"></div></div>';var back=document.createElement('div');back.className='ds-fashion-search-backdrop';document.body.append(back,o);$('.ds-fashion-search-slot',o).append(native);if(btn){btn.textContent='';btn.insertAdjacentHTML('afterbegin',icons.search)}var sug=$('.ds-fashion-search-suggestions',o);sug.innerHTML=phrases.slice(0,5).map(function(p){return'<button class="ds-fashion-search-suggestion" type="button" data-search="'+p+'">'+p+'</button>'}).join('');sug.onclick=function(e){var t=e.target.closest('[data-search]');if(!t)return;input.value=t.dataset.search;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()};$('.ds-fashion-search-close',o).onclick=closeSearch;back.onclick=closeSearch;var idx=0;input.placeholder='Hľadať: '+phrases[idx];setInterval(function(){if(input.value||document.activeElement===input)return;idx=(idx+1)%phrases.length;input.placeholder='Hľadať: '+phrases[idx]},1900);document.addEventListener('keydown',function(e){if(e.key==='Escape')closeSearch()})}
function mobileButton(){var top=$('#header .header-top');if(!top||$('.ds-fashion-mobile-menu',top))return;var b=action('ds-fashion-mobile-menu','Menu',icons.menu);top.prepend(b);b.onclick=function(){closeSearch();document.body.classList.toggle('navigation-window-visible')}}
function sticky(){var h=$('#header.ds-fashion-header');if(!h)return;h.classList.toggle('is-stuck',!document.body.classList.contains('in-index')||window.scrollY>42);searchTop()}
function boot(){var h=$('#header');if(!h)return;h.classList.add('ds-fashion-header');var tries=0;function build(){var items=menuItems();if(items.length){announcement(items);renderNav(items)}else if(tries++<20)setTimeout(build,150)}build();mountActions();mountSearch();mobileButton();sticky();addEventListener('scroll',sticky,{passive:true});addEventListener('resize',searchTop,{passive:true});addEventListener('storage',syncWish)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();